# Generated by Django 4.1 on 2024-06-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_record_created_at_record_deadline_record_importance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="importance",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=1,
                null=True,
            ),
        ),
    ]
