# Generated by Django 5.0.3 on 2024-06-30 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_record_importance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="record",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="record",
            name="importance",
        ),
        migrations.RemoveField(
            model_name="record",
            name="language",
        ),
        migrations.RemoveField(
            model_name="record",
            name="tags",
        ),
    ]
